### ISSUE TITLE
Timeouts don't cause restart/reconnect

### ISSUE THREAD

**Issue by esteigler** [huntwelch/MongoBot#24]
Once in a while Mongobot will disconnect from the channel with the parting message of:

```
20:23 -!- MongoBot [~macrotic@286.386.486.586] has quit [Ping timeout: 260 seconds]
```

After about 10 minutes of no reconnection I logged in and killed the process. When it restarted it reconnected and was back to normal.

**Comment by huntwelch** [comment]
Can't access the log right now, but there's probably something it could watch for in the ping request, and reboot upon finding.

**Comment by huntwelch** [comment]
Pretty sure this is fixed with the doctor.
